# Week 7: Independent Lab
Author: Jen Estes \
Course: BGEN 632 - Introduction to Python \
Term: Spring 2025 \
Due Date: April 14th, 2025 

This notebook contains code for the pre-process of data from 61 hospitals in California along with personnel data containing employee information. This program manipulates the data to provide a clean start for the Business Intelligence team, which is going to perform descriptive analyses. 

----

## Importing Modules

In [20]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold

## Setting Working Directory

In [22]:
os.chdir("/Users/jenestes/Desktop/week7labs/data") 
os.getcwd() 

'/Users/jenestes/Desktop/week7labs/data'

## Merging the Data 
This section of my program loads both the Hospital and Personnel Data and inspects the tables, and then merges the two data frames on the "HospitalID" variable. Then, the specified columns are deleted to create the merged data file before exporting. 

In [24]:
# Load Data - Both files and inspect them
# Hospital Data
hospital_data = pd.read_csv("CaliforniaHospitalData.csv")
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   HospitalID   61 non-null     int64  
 1   Name         61 non-null     object 
 2   Zip          61 non-null     object 
 3   Website      61 non-null     object 
 4   TypeControl  61 non-null     object 
 5   Teaching     61 non-null     object 
 6   DonorType    61 non-null     object 
 7   NoFTE        61 non-null     float64
 8   NetPatRev    61 non-null     float64
 9   InOperExp    61 non-null     float64
 10  OutOperExp   61 non-null     float64
 11  OperRev      61 non-null     int64  
 12  OperInc      61 non-null     int64  
 13  AvlBeds      61 non-null     int64  
dtypes: float64(4), int64(4), object(6)
memory usage: 6.8+ KB


In [25]:
# Personnel Data
personnel_data = pd.read_csv("CaliforniaHospitalData_Personnel.txt", delimiter = "\t")
personnel_data

,HospitalID,Work_ID,LastName,FirstName,Gender,PositionID,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,35665,351131,Cherukuri,Dileep,M,4,Safety Inspection Member,23987,2,1/1/2019,405-564-5580,dileep.cherukuri@okstate.edu
1,12145,756481,Rodriguez,Jose,M,1,Regional Representative,46978,4,1/1/2009,405-744-2238,jose.rodriguez@edihealth.com
2,45771,756481,Rodriguez,Jose,M,1,Regional Representative,46978,4,1/1/2011,405-744-2238,jose.rodriguez@edihealth.com
3,43353,756481,Rodriguez,Jose,M,4,Safety Inspection Member,23987,2,1/1/2011,405-744-2238,jose.rodriguez@edihealth.com
4,17718,811240,Charles,Kenneth,M,1,Regional Representative,46978,4,1/1/2009,405-744-3412,kenneth.charles@edihealth.com
...,...,...,...,...,...,...,...,...,...,...,...,...
59,33283,704360,Frank,Vernon,M,1,Regional Representative,46978,4,1/1/2012,801-687-2845,vernon.frank@ihc.com
60,33242,704360,Frank,Vernon,M,4,Safety Inspection Member,23987,2,1/1/2011,801-687-2845,vernon.frank@ihc.com
61,46342,768057,Tanner,Patricia,F,3,Acting Director,248904,8,1/1/2011,801-687-7877,patricia.tanner@prohealth.net
62,43437,768057,Tanner,Patricia,F,1,Regional Representative,46978,4,1/1/2010,801-687-7877,patricia.tanner@prohealth.net


In [31]:
# Merging the data on HospitalID
merged_hospital = hospital_data.merge(personnel_data, how = 'inner', on = "HospitalID")
merged_hospital

,HospitalID,Name,Zip,Website,TypeControl,Teaching,DonorType,NoFTE,NetPatRev,InOperExp,...,LastName,FirstName,Gender,PositionID,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,45740,Mammoth Hospital,93546-0660,www.mammothhospital.com,District,Small/Rural,Charity,327.0,1.355202e+05,2.052343e+07,...,Web,David,M,4,Safety Inspection Member,23987,2,1/1/2012,785-532-2452,david.web@comenitymed.com
1,12145,Victor Valley Community Hospital,92392,www.vvch.org,Non Profit,Small/Rural,Charity,345.0,1.361567e+05,3.344754e+07,...,Rodriguez,Jose,M,1,Regional Representative,46978,4,1/1/2009,405-744-2238,jose.rodriguez@edihealth.com
2,25667,Pioneers Memorial Hospital,92227,www.pmhd.org,District,Small/Rural,Charity,601.2,1.970943e+05,3.725418e+07,...,Adamson,David,M,1,Regional Representative,46978,4,1/1/2012,785-532-7573,david.adamson@txbiomed.net
3,46996,Ridgecrest Regional Hospital,93555,www.rrh.org,Non Profit,Small/Rural,Charity,400.0,1.391704e+05,2.338557e+07,...,Roberts,Melissa,F,4,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
4,37393,Barstow Community Hospital,92311,www.barstowhospital.com,Investor,Small/Rural,Charity,262.0,1.167978e+05,1.368450e+07,...,Iwata,Akira,M,1,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,32930,Scripps Mercy Hospital,92103,www.scrippshealth.org,Non Profit,Teaching,Alumni,2814.0,1.321032e+06,3.791029e+08,...,Manin,Emily,F,1,Regional Representative,46978,4,1/1/2011,801-223-6845,emily.manin@ihc.com
57,31032,Long Beach Memorial & Miller Children's Hospital,90806,www.memorialcare.org,Non Profit,Teaching,Alumni,5218.0,1.187022e+06,2.912481e+08,...,Dong,HongWei,F,4,Safety Inspection Member,23987,2,1/1/2012,479-354-4864,hongwei.dong@brokenhealth.com
58,22460,Stanford Hospital & Clinics,94305,stanfordhospital.org,Non Profit,Teaching,Alumni,6392.0,4.333934e+06,9.289621e+08,...,Smith,Mary,F,4,Safety Inspection Member,23987,2,1/1/2012,469-767-5485,mary.smith@ihc.com
59,33192,California Pacific Medical Center - Pacific Ca...,94115,www.cpmc.org,Non Profit,Teaching,Alumni,1565.1,2.736281e+06,6.337903e+08,...,Fourier,Craig,M,1,Regional Representative,46978,4,1/1/2011,503-235-4877,craig.fourier@comenitymed.com


In [33]:
# Finding duplicate columns- None
merged_hospital.columns

Index(['HospitalID', 'Name', 'Zip', 'Website', 'TypeControl', 'Teaching',
       'DonorType', 'NoFTE', 'NetPatRev', 'InOperExp', 'OutOperExp', 'OperRev',
       'OperInc', 'AvlBeds', 'Work_ID', 'LastName', 'FirstName', 'Gender',
       'PositionID', 'PositionTitle', 'Compensation', 'MaxTerm', 'StartDate',
       'Phone', 'Email'],
      dtype='object')

In [35]:
# Removing Columns- Work_ID, PositionID, Website
final_hospital = merged_hospital.drop(['Work_ID', 'PositionID', 'Website'], axis = 1)
final_hospital

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,NoFTE,NetPatRev,InOperExp,OutOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,45740,Mammoth Hospital,93546-0660,District,Small/Rural,Charity,327.0,1.355202e+05,2.052343e+07,3.491622e+07,...,15,Web,David,M,Safety Inspection Member,23987,2,1/1/2012,785-532-2452,david.web@comenitymed.com
1,12145,Victor Valley Community Hospital,92392,Non Profit,Small/Rural,Charity,345.0,1.361567e+05,3.344754e+07,2.034860e+07,...,99,Rodriguez,Jose,M,Regional Representative,46978,4,1/1/2009,405-744-2238,jose.rodriguez@edihealth.com
2,25667,Pioneers Memorial Hospital,92227,District,Small/Rural,Charity,601.2,1.970943e+05,3.725418e+07,3.783245e+07,...,107,Adamson,David,M,Regional Representative,46978,4,1/1/2012,785-532-7573,david.adamson@txbiomed.net
3,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.0,1.391704e+05,2.338557e+07,2.466136e+07,...,55,Roberts,Melissa,F,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
4,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.0,1.167978e+05,1.368450e+07,1.515999e+07,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,32930,Scripps Mercy Hospital,92103,Non Profit,Teaching,Alumni,2814.0,1.321032e+06,3.791029e+08,1.064302e+08,...,530,Manin,Emily,F,Regional Representative,46978,4,1/1/2011,801-223-6845,emily.manin@ihc.com
57,31032,Long Beach Memorial & Miller Children's Hospital,90806,Non Profit,Teaching,Alumni,5218.0,1.187022e+06,2.912481e+08,1.093286e+08,...,462,Dong,HongWei,F,Safety Inspection Member,23987,2,1/1/2012,479-354-4864,hongwei.dong@brokenhealth.com
58,22460,Stanford Hospital & Clinics,94305,Non Profit,Teaching,Alumni,6392.0,4.333934e+06,9.289621e+08,6.621559e+08,...,445,Smith,Mary,F,Safety Inspection Member,23987,2,1/1/2012,469-767-5485,mary.smith@ihc.com
59,33192,California Pacific Medical Center - Pacific Ca...,94115,Non Profit,Teaching,Alumni,1565.1,2.736281e+06,6.337903e+08,2.960207e+08,...,730,Fourier,Craig,M,Regional Representative,46978,4,1/1/2011,503-235-4877,craig.fourier@comenitymed.com


## Exporting the Data
This section of my program involves filtering the data to our interests, which is selecting Small/Rural hospitals that have 15 or more available beds with a positive operating income. This data frame is exported as a tab-delimited file called`hospital_data_new.txt`, which is saved in the directory `data`.

In [40]:
# Final changes to DataFrame: Small/Rural with at least 15 beds and positive operating income
export_data = final_hospital[(final_hospital.Teaching == 'Small/Rural') & (final_hospital.AvlBeds >= 15) & (final_hospital.OperInc > 0) ]

In [42]:
# Converting to file in Data folder- See references 
export_data.to_csv('hospital_data_new.txt', sep = "\t", index = False)

## Renaming Columns 
This section of my program re-opens the newly created data frame and renames columns based on the assignment requirements. 

In [45]:
# Re-opening the newly created DataFrame
ca_hospitals = pd.read_csv("hospital_data_new.txt", delimiter = "\t")
ca_hospitals

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,NoFTE,NetPatRev,InOperExp,OutOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.00,139170.37980,2.338557e+07,2.466136e+07,...,55,Roberts,Melissa,F,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
1,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.00,116797.83060,1.368450e+07,1.515999e+07,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
2,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.50,232503.01910,3.668289e+07,3.673926e+07,...,66,Marlin,Bill,M,Safety Inspection Member,23987,2,1/1/2011,503-645-7508,bill.marlin@larcmed.com
3,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.50,214516.44810,3.270922e+07,4.357185e+07,...,65,Johanson,Sandy,F,Regional Representative,46978,4,1/1/2012,801-216-4821,sandy.johanson@ihc.com
4,29823,Colusa Regional Medical Center,95932-2954,Non Profit,Small/Rural,Charity,168.00,51726.49180,9.022366e+06,1.040251e+07,...,48,Tanner,Patricia,F,Acting Director,248904,8,1/1/2009,801-687-7877,patricia.tanner@prohealth.net
5,13738,St. Mary Medical Center,92307-2206,Non Profit,Small/Rural,Charity,1216.00,540975.11750,1.251283e+08,6.680154e+07,...,186,Milgrom,Patricia,F,Safety Inspection Member,23987,2,1/1/2011,479-178-9584,patricia.milgrom@brokenhealth.com
6,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.00,335179.55740,5.358904e+07,6.703015e+07,...,119,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
7,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.00,335179.55740,5.358904e+07,6.703015e+07,...,119,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
8,33207,Memorial Hospital - Los Banos,93635-3419,Non Profit,Small/Rural,Charity,235.00,105166.89340,1.506597e+07,2.333806e+07,...,48,Charles,Kenneth,M,State Board Representative,89473,3,1/1/2010,405-744-3412,kenneth.charles@edihealth.com
9,44817,Fairchild Medical Center,96097-3450,Non Profit,Small/Rural,Charity,250.00,108162.91260,1.485974e+07,2.362366e+07,...,25,Marlin,Bill,M,State Board Representative,89473,3,1/1/2010,503-645-7508,bill.marlin@larcmed.com


In [47]:
# Renaming Columns
ca_hospitals.rename(columns = {'NoFTE':'FullTimeCount'}, inplace = True)

ca_hospitals.rename(columns = {'NetPatRev':'NetPatientRevenue'}, inplace = True)

ca_hospitals.rename(columns = {'InOperExp':'InpatientOperExp'}, inplace = True)

ca_hospitals.rename(columns = {'OutOperExp':'OutpatientOperExp'}, inplace = True)

ca_hospitals.rename(columns = {'OperRev':'Operating_Revenue'}, inplace = True)

ca_hospitals.rename(columns = {'OperInc':'Operating_Income'}, inplace = True)

ca_hospitals.columns   # Success!

Index(['HospitalID', 'Name', 'Zip', 'TypeControl', 'Teaching', 'DonorType',
       'FullTimeCount', 'NetPatientRevenue', 'InpatientOperExp',
       'OutpatientOperExp', 'Operating_Revenue', 'Operating_Income', 'AvlBeds',
       'LastName', 'FirstName', 'Gender', 'PositionTitle', 'Compensation',
       'MaxTerm', 'StartDate', 'Phone', 'Email'],
      dtype='object')

## Inserting Records
This section of my program involves inserting 2 new records into the data frame. I have added myself as a "Safety Inspection Member" to the hospitals with IDs 38798 and 33207. I have filled in the rest of the variables according to those hospitals and my information, and I check to make sure these two rows were added to the newly merged data. 

In [50]:
# Looking at data in a certain row
# I am adding myself to hospitalID 38798 and 33207, I obtained this information from looking at index 6 and 8
#ca_hospitals.iloc[6]
#ca_hospitals.iloc[8]

In [52]:
# Inserting myself into these new rows
new_rows = pd.DataFrame({'HospitalID': [38798, 33207],
                         'Name': ["Goleta Valley Cottage Hospital", "Memorial Hospital - Los Banos"],
                         'Zip':[93111, 93635-3419],
                         'TypeControl': ["Non Profit", "Non Profit"],
                         'Teaching': ["Small/Rural", "Small/Rural"],
                         'DonorType': ["Charity", "Charity"],
                         'FullTimeCount': [288.0, 235.0],
                         'NetPatientRevenue': [335179.5574, 105166.8934],
                         'InpatientOperExp': [53589036.09, 15065967.36],
                         'OutpatientOperExp': [67030147.91, 23338063.64],
                         'Operating_Revenue': [126303054, 39282960],
                         'Operating_Income': [5683870, 878929],
                         'AvlBeds': [119, 48],
                         'LastName': ["Estes", "Estes"], 
                         'FirstName': ["Jen", "Jen"],
                         'Gender': ["F", "F"],
                        'PositionTitle': ["Safety Inspection Member","Safety Inspection Member"],
                        'Compensation': [23987, 23987],
                        'MaxTerm': [2,2],
                        'StartDate': ["4/9/2025", "4/9/2025"],
                        'Phone': [425-505-1130, 425-505-1130],
                        'Email': ["bigred0606@gmail.com", "bigred0606@gmail.com"]},
                        index = [28,29]
                       )

In [54]:
# Using concat to add the new rows to the dataframe, and saving it as new_merge
new_merge = pd.concat([ca_hospitals, new_rows], ignore_index = True)
new_merge

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.00,139170.37980,2.338557e+07,2.466136e+07,...,55,Roberts,Melissa,F,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
1,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.00,116797.83060,1.368450e+07,1.515999e+07,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
2,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.50,232503.01910,3.668289e+07,3.673926e+07,...,66,Marlin,Bill,M,Safety Inspection Member,23987,2,1/1/2011,503-645-7508,bill.marlin@larcmed.com
3,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.50,214516.44810,3.270922e+07,4.357185e+07,...,65,Johanson,Sandy,F,Regional Representative,46978,4,1/1/2012,801-216-4821,sandy.johanson@ihc.com
4,29823,Colusa Regional Medical Center,95932-2954,Non Profit,Small/Rural,Charity,168.00,51726.49180,9.022366e+06,1.040251e+07,...,48,Tanner,Patricia,F,Acting Director,248904,8,1/1/2009,801-687-7877,patricia.tanner@prohealth.net
5,13738,St. Mary Medical Center,92307-2206,Non Profit,Small/Rural,Charity,1216.00,540975.11750,1.251283e+08,6.680154e+07,...,186,Milgrom,Patricia,F,Safety Inspection Member,23987,2,1/1/2011,479-178-9584,patricia.milgrom@brokenhealth.com
6,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.00,335179.55740,5.358904e+07,6.703015e+07,...,119,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
7,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.00,335179.55740,5.358904e+07,6.703015e+07,...,119,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
8,33207,Memorial Hospital - Los Banos,93635-3419,Non Profit,Small/Rural,Charity,235.00,105166.89340,1.506597e+07,2.333806e+07,...,48,Charles,Kenneth,M,State Board Representative,89473,3,1/1/2010,405-744-3412,kenneth.charles@edihealth.com
9,44817,Fairchild Medical Center,96097-3450,Non Profit,Small/Rural,Charity,250.00,108162.91260,1.485974e+07,2.362366e+07,...,25,Marlin,Bill,M,State Board Representative,89473,3,1/1/2010,503-645-7508,bill.marlin@larcmed.com


In [56]:
# Test to see if new rows were added
print(len(ca_hospitals.index.values))  # original DataFrame

print(len(new_merge.index.values))  # new DataFrame

28
30


## Filtering Data
This section of my program filters the data to select all hospitals that are non-profit with more than 250 employees, unless the net patient revenue is smaller than \$109,000. I also remove the columns containing employee information and save it as a new data frame, which is `new_merge2`. Then, I select all the *Regional Representatives* who work at a hospital with operating income greater than \$100,000, and save this as a new data frame, which is `new_merge3`.

In [59]:
# Hospitals that are non-profit with more than 250 employees, or net patient revenue less than $109,000
new_merge2 = new_merge[((new_merge.TypeControl == 'Non Profit') & (new_merge.FullTimeCount > 250)) | (new_merge.NetPatientRevenue < 109000) ]
new_merge2

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
0,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.0,139170.37980,2.338557e+07,2.466136e+07,...,55,Roberts,Melissa,F,Safety Inspection Member,23987,2,1/1/2009,785-532-9779,melissa.roberts@txbiomed.net
2,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.5,232503.01910,3.668289e+07,3.673926e+07,...,66,Marlin,Bill,M,Safety Inspection Member,23987,2,1/1/2011,503-645-7508,bill.marlin@larcmed.com
3,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.5,214516.44810,3.270922e+07,4.357185e+07,...,65,Johanson,Sandy,F,Regional Representative,46978,4,1/1/2012,801-216-4821,sandy.johanson@ihc.com
4,29823,Colusa Regional Medical Center,95932-2954,Non Profit,Small/Rural,Charity,168.0,51726.49180,9.022366e+06,1.040251e+07,...,48,Tanner,Patricia,F,Acting Director,248904,8,1/1/2009,801-687-7877,patricia.tanner@prohealth.net
5,13738,St. Mary Medical Center,92307-2206,Non Profit,Small/Rural,Charity,1216.0,540975.11750,1.251283e+08,6.680154e+07,...,186,Milgrom,Patricia,F,Safety Inspection Member,23987,2,1/1/2011,479-178-9584,patricia.milgrom@brokenhealth.com
6,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.0,335179.55740,5.358904e+07,6.703015e+07,...,119,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
7,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.0,335179.55740,5.358904e+07,6.703015e+07,...,119,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
8,33207,Memorial Hospital - Los Banos,93635-3419,Non Profit,Small/Rural,Charity,235.0,105166.89340,1.506597e+07,2.333806e+07,...,48,Charles,Kenneth,M,State Board Representative,89473,3,1/1/2010,405-744-3412,kenneth.charles@edihealth.com
9,44817,Fairchild Medical Center,96097-3450,Non Profit,Small/Rural,Charity,250.0,108162.91260,1.485974e+07,2.362366e+07,...,25,Marlin,Bill,M,State Board Representative,89473,3,1/1/2010,503-645-7508,bill.marlin@larcmed.com
11,20231,Hanford Community Medical Center,93230-3513,Non Profit,Small/Rural,Charity,777.0,363127.59560,5.370467e+07,7.058208e+07,...,121,Flemming,Kris,F,State Board Representative,89473,3,1/1/2012,503-758-9066,kris.flemming@larcmed.com


In [61]:
# Removing columns with employee information from new_merge2
#new_merge2.columns    # Checking out columns that need to be deleted
new_merge2 = new_merge2.drop(['LastName', 'FirstName', 'Gender', 'PositionTitle', 'Compensation',
       'MaxTerm', 'StartDate', 'Phone', 'Email'], axis = 1)

In [63]:
# Checking that these changes were saved
new_merge2                                          

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,Operating_Revenue,Operating_Income,AvlBeds
0,46996,Ridgecrest Regional Hospital,93555,Non Profit,Small/Rural,Charity,400.0,139170.37980,2.338557e+07,2.466136e+07,51087341,3040415,55
2,17741,St. Elizabeth Community Hospital,96080,Non Profit,Small/Rural,Charity,397.5,232503.01910,3.668289e+07,3.673926e+07,85808509,12386360,66
3,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.5,214516.44810,3.270922e+07,4.357185e+07,79005075,2724001,65
4,29823,Colusa Regional Medical Center,95932-2954,Non Profit,Small/Rural,Charity,168.0,51726.49180,9.022366e+06,1.040251e+07,19445901,21025,48
5,13738,St. Mary Medical Center,92307-2206,Non Profit,Small/Rural,Charity,1216.0,540975.11750,1.251283e+08,6.680154e+07,199873795,7943967,186
6,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.0,335179.55740,5.358904e+07,6.703015e+07,126303054,5683870,119
7,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.0,335179.55740,5.358904e+07,6.703015e+07,126303054,5683870,119
8,33207,Memorial Hospital - Los Banos,93635-3419,Non Profit,Small/Rural,Charity,235.0,105166.89340,1.506597e+07,2.333806e+07,39282960,878929,48
9,44817,Fairchild Medical Center,96097-3450,Non Profit,Small/Rural,Charity,250.0,108162.91260,1.485974e+07,2.362366e+07,40140721,1657323,25
11,20231,Hanford Community Medical Center,93230-3513,Non Profit,Small/Rural,Charity,777.0,363127.59560,5.370467e+07,7.058208e+07,134067466,9780718,121


In [65]:
# Regional Representatives who work at a hospital with operating income greater than $100,000
new_merge3 = new_merge[((new_merge.PositionTitle == 'Regional Representative') & (new_merge.Operating_Income>100000))]
new_merge3

,HospitalID,Name,Zip,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,...,AvlBeds,LastName,FirstName,Gender,PositionTitle,Compensation,MaxTerm,StartDate,Phone,Email
1,37393,Barstow Community Hospital,92311,Investor,Small/Rural,Charity,262.0,116797.83060,1.368450e+07,1.515999e+07,...,42,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
3,20277,Ukiah Valley Medical Center,95482,Non Profit,Small/Rural,Charity,503.5,214516.44810,3.270922e+07,4.357185e+07,...,65,Johanson,Sandy,F,Regional Representative,46978,4,1/1/2012,801-216-4821,sandy.johanson@ihc.com
6,38798,Goleta Valley Cottage Hospital,93111,Non Profit,Small/Rural,Charity,288.0,335179.55740,5.358904e+07,6.703015e+07,...,119,Iwata,Akira,M,Regional Representative,46978,4,1/1/2011,801-611-9161,akira.iwata@hsu.edu
7,46348,Barton Memorial Hospital,96150,Non Profit,Small/Rural,Charity,750.0,335179.55740,5.358904e+07,6.703015e+07,...,119,Paanua,Kaaluai,M,Regional Representative,46978,4,1/1/2011,479-684-1883,kaaluai.paanua@brokenhealth.com
10,17718,Mercy Medical Center - Mount Shasta,96067,Non Profit,Small/Rural,Charity,215.5,123480.27050,2.200350e+07,2.241005e+07,...,60,Charles,Kenneth,M,Regional Representative,46978,4,1/1/2009,405-744-3412,kenneth.charles@edihealth.com
20,20266,Sonora Regional Medical Center - greenley,95370,Non Profit,Small/Rural,Charity,779.0,367540.66390,6.822885e+07,6.996886e+07,...,152,Adams,Sandy,F,Regional Representative,46978,4,1/1/2009,785-532-3333,sandy.adams@comenitymed.com
23,38802,Santa Ynez Valley Cottage Hospital,93463,Non Profit,Small/Rural,Charity,67.0,28773.45355,1.780969e+06,8.235088e+06,...,20,Dong,HongWei,F,Regional Representative,46978,4,1/1/2010,479-354-4864,hongwei.dong@brokenhealth.com
27,19868,Ojai Valley Community Hospital,93023-3163,Non Profit,Small/Rural,Charity,180.0,59504.62295,1.195530e+07,1.032680e+07,...,103,Coulter,Tracy,F,Regional Representative,46978,4,1/1/2010,785-532-6548,tracy.coulter@wou.edu


## Convert Date-Time Data
Using the `new_merge` DataFrame, I convert the date-time columns into a datetime datatype. I then confirm these changes by outputting the data types for all columns, and output the first 5 records of the column I converted.

In [68]:
# Convert any date-time columns to datetime datatype
new_merge.dtypes  # Need to convert StartDate
new_merge.StartDate.head(30)

0     1/1/2009
1     1/1/2011
2     1/1/2011
3     1/1/2012
4     1/1/2009
5     1/1/2011
6     1/1/2011
7     1/1/2011
8     1/1/2010
9     1/1/2010
10    1/1/2009
11    1/1/2012
12    1/1/2010
13    1/1/2010
14    1/1/2011
15    1/1/2009
16    1/1/2012
17    1/1/2005
18    1/1/2011
19    1/1/2011
20    1/1/2009
21    1/1/2012
22    1/1/2006
23    1/1/2010
24    1/1/2012
25    1/1/2005
26    1/1/2003
27    1/1/2010
28    4/9/2025
29    4/9/2025
Name: StartDate, dtype: object

In [70]:
# Converting StartDate to datetime
new_merge['StartDate'] = pd.to_datetime(new_merge['StartDate'])

In [72]:
# Output the first 5 records of the converted columns
new_merge.StartDate.head(5)

0   2009-01-01
1   2011-01-01
2   2011-01-01
3   2012-01-01
4   2009-01-01
Name: StartDate, dtype: datetime64[ns]

## References

### Reference 1
In order to export my DataFrame to my data folder, I used information on the pandas documentation to help figure this out and make sure I understood the process. This resource helped me with my code in block 42: "export_data.to_csv('hospital_data_new.txt', sep = "\t", index = False)".

URL: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html
